"""Internal adapter boundary for ProjectOps integrations."""

from projectops.adapters.base import AdapterRequest, AdapterResponse
from projectops.adapters.channel_rendering import (
    ChannelRenderPolicy,
    get_channel_render_policy,
    render_event_for_channel,
    render_transcript_for_channel,
)
from projectops.adapters.confirmation import (
    ConfirmationState,
    confirm_request,
    is_confirmation_response,
    prepare_confirmation,
    reject_request,
)
from projectops.adapters.diagnostics import (
    DIAGNOSTIC_VERSION,
    DiagnosticEvent,
    DiagnosticWriter,
    create_diagnostic_event,
    diagnostic_event_to_json_line,
    sanitize_diagnostic_metadata,
)
from projectops.adapters.events import (
    AdapterEvent,
    AdapterTranscript,
    event_from_turn_result,
    event_to_display_line,
    transcript_from_turns,
)
from projectops.adapters.explicit_confirmation import (
    ExplicitConfirmationCheck,
    ExplicitConfirmationPrompt,
    build_explicit_confirmation_phrase,
    check_explicit_confirmation,
    create_explicit_confirmation_prompt,
    is_explicit_confirmation_required,
    summarize_explicit_confirmation_prompt,
)
from projectops.adapters.intent_mapper import IntentMappingResult, map_text_to_adapter_request
from projectops.adapters.local_wrapper import (
    LocalBridgeWrapper,
    PendingExplicitConfirmation,
    WrapperRouteResult,
)
from projectops.adapters.permissions import (
    AdapterActionPolicy,
    PermissionDecision,
    evaluate_action_permission,
    get_action_policy,
    is_mutating_action,
    is_read_only_action,
    is_sensitive_action,
    is_supported_action,
)
from projectops.adapters.permission_preflight import (
    PermissionPreflightResult,
    permission_preflight_result_to_payload,
    preflight_adapter_request,
    preflight_openclaw_payload,
    preflight_text_command,
)
from projectops.adapters.replay_protection import (
    CONFIRMATION_STATE_CONSUMED,
    CONFIRMATION_STATE_PENDING,
    CONFIRMATION_STATE_REJECTED,
    CONFIRMATION_STATE_UNKNOWN,
    ConfirmationReplayCheck,
    ConfirmationReplayGuard,
    ConfirmationReplayRecord,
)
from projectops.adapters.renderers import (
    render_event_as_text,
    render_event_summary,
    render_transcript_as_text,
)
from projectops.adapters.session import AdapterSession, AdapterTurnResult
from projectops.adapters.session_store import (
    AdapterSessionStore,
    InMemoryAdapterSessionStore,
)
from projectops.adapters.service_adapter import ProjectOpsServiceAdapter
from projectops.adapters.wrapper_notifications import (
    EXPLICIT_CONFIRMATION_MISMATCH_NOTIFICATION_TYPE,
    MISSING_CONFIRMATION_NOTIFICATION_TYPE,
    REJECTED_CONFIRMATION_REPLAY_NOTIFICATION_TYPE,
    SESSION_LOSS_MESSAGE,
    SESSION_LOSS_NOTIFICATION_TYPE,
    STALE_CONFIRMATION_REPLAY_NOTIFICATION_TYPE,
    WrapperNotification,
    create_explicit_confirmation_mismatch_notification,
    create_missing_confirmation_notification,
    create_pending_cleared_notification,
    create_rejected_confirmation_replay_notification,
    create_session_loss_notification,
    create_stale_confirmation_replay_notification,
    is_retry_safe_after_session_loss,
    notification_from_wrapper_error,
    wrapper_notification_to_payload,
    wrapper_notification_to_text,
)
from projectops.adapters.wrapper_rendering import (
    render_wrapper_notification_for_channel,
    render_wrapper_result_as_text,
    render_wrapper_result_payload,
    render_wrapper_result_summary,
)
from projectops.adapters.wrapper_transcript import (
    WrapperTranscript,
    WrapperTranscriptEntry,
    create_wrapper_transcript_entry,
    run_payloads_with_transcript,
    sanitize_transcript_payload,
    transcript_to_json,
    transcript_to_markdown,
)

__all__ = [
    "AdapterEvent",
    "AdapterActionPolicy",
    "AdapterRequest",
    "AdapterResponse",
    "AdapterSession",
    "AdapterSessionStore",
    "AdapterTranscript",
    "AdapterTurnResult",
    "ChannelRenderPolicy",
    "ConfirmationState",
    "CONFIRMATION_STATE_CONSUMED",
    "CONFIRMATION_STATE_PENDING",
    "CONFIRMATION_STATE_REJECTED",
    "CONFIRMATION_STATE_UNKNOWN",
    "DIAGNOSTIC_VERSION",
    "ConfirmationReplayCheck",
    "ConfirmationReplayGuard",
    "ConfirmationReplayRecord",
    "DiagnosticEvent",
    "DiagnosticWriter",
    "EXPLICIT_CONFIRMATION_MISMATCH_NOTIFICATION_TYPE",
    "ExplicitConfirmationCheck",
    "ExplicitConfirmationPrompt",
    "InMemoryAdapterSessionStore",
    "IntentMappingResult",
    "LocalBridgeWrapper",
    "MISSING_CONFIRMATION_NOTIFICATION_TYPE",
    "PermissionDecision",
    "PermissionPreflightResult",
    "PendingExplicitConfirmation",
    "ProjectOpsServiceAdapter",
    "REJECTED_CONFIRMATION_REPLAY_NOTIFICATION_TYPE",
    "SESSION_LOSS_MESSAGE",
    "STALE_CONFIRMATION_REPLAY_NOTIFICATION_TYPE",
    "WrapperRouteResult",
    "WrapperNotification",
    "WrapperTranscript",
    "WrapperTranscriptEntry",
    "build_explicit_confirmation_phrase",
    "check_explicit_confirmation",
    "confirm_request",
    "create_explicit_confirmation_mismatch_notification",
    "create_missing_confirmation_notification",
    "create_pending_cleared_notification",
    "create_rejected_confirmation_replay_notification",
    "create_session_loss_notification",
    "create_stale_confirmation_replay_notification",
    "create_explicit_confirmation_prompt",
    "create_diagnostic_event",
    "create_wrapper_transcript_entry",
    "diagnostic_event_to_json_line",
    "evaluate_action_permission",
    "event_from_turn_result",
    "event_to_display_line",
    "get_channel_render_policy",
    "get_action_policy",
    "is_confirmation_response",
    "is_explicit_confirmation_required",
    "is_mutating_action",
    "is_read_only_action",
    "is_sensitive_action",
    "is_supported_action",
    "map_text_to_adapter_request",
    "notification_from_wrapper_error",
    "permission_preflight_result_to_payload",
    "preflight_adapter_request",
    "preflight_openclaw_payload",
    "preflight_text_command",
    "prepare_confirmation",
    "render_event_for_channel",
    "render_event_as_text",
    "render_event_summary",
    "render_transcript_for_channel",
    "render_transcript_as_text",
    "render_wrapper_notification_for_channel",
    "render_wrapper_result_as_text",
    "render_wrapper_result_payload",
    "render_wrapper_result_summary",
    "reject_request",
    "run_payloads_with_transcript",
    "sanitize_transcript_payload",
    "sanitize_diagnostic_metadata",
    "SESSION_LOSS_NOTIFICATION_TYPE",
    "summarize_explicit_confirmation_prompt",
    "transcript_from_turns",
    "transcript_to_json",
    "transcript_to_markdown",
    "is_retry_safe_after_session_loss",
    "wrapper_notification_to_payload",
    "wrapper_notification_to_text",
]
